id: I46463645
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:12:27+00:00'
last_modified: '2022-06-08T06:00:01.677469+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29641
  title: གནས་མཆོག་ས་སྐྱ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    1DC1:
      image_group_id: I1PD28054
      title: ''
      total_pages: 218
      order: 1
      base_file: 1DC1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
